repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff format
        entry: ruff format
        fail_fast: true
        language: system
        types: [python]
      - id: ruff
        name: ruff check
        entry: ruff check
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
