[project]
name = "pySigma-backend-netwitness"
version = "0.2.5"
description = "pySigma NetWitness backend"
readme = "README.md"
authors = [
    {name = "Marcel Kwaschny", email = "dev@marcelkwaschny.de"}
]
license = "LGPL-2.1-only"
requires-python = ">=3.10"
dependencies = [
    "pysigma>=0.11.0"
]

[project.urls]
repository = "https://github.com/marcelkwaschny/pySigma-backend-netwitness"

[dependency-groups]
dev = [
    "defusedxml==0.7.1",
    "mypy==1.18.2",
    "pre-commit==4.3.0",
    "pytest-cov==7.0.0",
    "pytest==8.4.2",
    "ruff==0.14.3",
]

[tool.ruff]
line-length = 120
exclude = [".venv", "venv", "print_coverage.py"]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["COM812", "D104", "D202", "D203", "D205", "D213", "D400", "D401", "D404", "D413", "D415", "RUF001", "S105"]

[tool.ruff.lint.extend-per-file-ignores]
"tests/**/*.py" = [
    "S101", # asserts allowed in tests
]

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
explicit_package_bases = true