name: Lint
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  formatting:
    strategy:
      matrix:
        os: [ 'ubuntu-24.04' ]
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.13"
      - name: Install dependencies
        run: uv sync --frozen
      - name: Run ruff
        run: uv run ruff format --check sigma tests

  ruff:
    strategy:
      matrix:
        os: [ 'ubuntu-24.04' ]
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.13"
      - name: Install dependencies
        run: uv sync --frozen
      - name: Run ruff
        run: uv run ruff check sigma tests

  mypy:
    strategy:
      matrix:
        os: [ 'ubuntu-24.04' ]
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.13"
      - name: Install dependencies
        run: uv sync --frozen
      - name: Run mypy
        run: uv run mypy sigma tests
