name: Release to PyPI
on:
  release:
    types: [published]
  push:
    tags:
      - v*.*.*

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.13"
      - name: Verify versioning
        run: |
          [ "$(uv version --short)" == "${GITHUB_REF#refs/tags/v}" ]
      - name: Install dependencies
        run: uv sync --frozen
      - name: Build package
        run: uv build
      - name: Publish to PyPI
        if: ${{ github.event_name == 'release' }}
        run: uv publish --publish-url https://pypi.org/legacy/ --token ${{ secrets.PYPI_API_TOKEN }}